Try custom build

diff --git a/.github/workflows/nx-cloud.yml b/.github/workflows/nx-cloud.yml
--- a/.github/workflows/nx-cloud.yml
+++ b/.github/workflows/nx-cloud.yml
@@ -9,16 +9,71 @@ on:
 jobs:
   build:
     name: Build affected files
-    uses: nrwl/ci/.github/workflows/nx-cloud-main.yml@v0.13.0
-    with:
-      main-branch-name: main
-      number-of-agents: 3
-      init-commands: |
-        npx nx-cloud start-ci-run --stop-agents-after="build" --agent-count=3
-      parallel-commands-on-agents: |
-        npx nx affected --target=lint --parallel=3
-        npx nx affected --target=format --parallel=3
-        npx nx affected --target=build --parallel=3
+    runs-on: ubuntu-latest
+    steps:
+      - uses: actions/checkout@v3
+        name: Checkout [Pull Request]
+        if: ${{ github.event_name == 'pull_request' }}
+        with:
+          # By default, PRs will be checked-out based on the Merge Commit, but we want the actual branch HEAD.
+          ref: ${{ github.event.pull_request.head.sha }}
+          # We need to fetch all branches and commits so that Nx affected has a base to compare against.
+          fetch-depth: 0
+
+      - uses: actions/checkout@v3
+        name: Checkout [Default Branch]
+        if: ${{ github.event_name != 'pull_request' }}
+        with:
+          # We need to fetch all branches and commits so that Nx affected has a base to compare against.
+          fetch-depth: 0
+
+      - name: Use Node.js 18
+        uses: actions/setup-node@v3
+        with:
+          node-version: 18.x
+          cache: 'npm'
+      - name: Install dependencies
+        run: npm ci
+      - name: Initialize Nx Cloud
+        run: npx nx-cloud start-ci-run
+      - name: Run commands in parallel
+        run: |
+          pids=()
+
+          # list of commands to be run on agents
+          npx nx affected --target=lint --parallel=3 &
+          pids+=($!)
+
+          npx nx affected --target=format --parallel=3 &
+          pids+=($!)
+
+          npx nx affected --target=build --parallel=3
+          pids+=($!)
+
+          # run all commands in parallel and bail if one of them fails
+          for pid in \${pids[*]}; do
+            if ! wait $pid; then
+              exit 1
+            fi
+          done
+
+          exit 0
+      - name: Stop all agents
+        # It's important that we always run this step, otherwise in the case of any failures in preceding non-Nx steps, the agents will keep running and waste billable minutes
+        if: ${{ always() }}
+        run: npx nx-cloud stop-all-agents
+
+
+    # uses: nrwl/ci/.github/workflows/nx-cloud-main.yml@v0.13.0
+    # with:
+    #   main-branch-name: main
+    #   number-of-agents: 3
+    #   init-commands: |
+    #     npx nx-cloud start-ci-run --stop-agents-after="build" --agent-count=3
+    #   parallel-commands-on-agents: |
+    #     npx nx affected --target=lint --parallel=3
+    #     npx nx affected --target=format --parallel=3
+    #     npx nx affected --target=build --parallel=3
   deploy:
     name: Deploy new build
     if: ${{ github.event_name != 'pull_request' }}
@@ -51,9 +106,3 @@ jobs:
             /ci-cd/assassin/cloudflare CLOUDFLARE_API_TOKEN
       - name: Deploy with Wrangler
         run: npm run deploy
-
-  agents:
-    name: Nx Cloud - Agents
-    uses: nrwl/ci/.github/workflows/nx-cloud-agents.yml@v0.13.0
-    with:
-      number-of-agents: 3
